---
dotfiles_repo: "https://github.com/GlaIZier/configs"
dotfiles_repo_version: master
dotfiles_repo_local_destination: "~/github/configs-macos-environment"
dotfiles_repo_accept_hostkey: false
dotfiles_files:
  - macos/.bashrc
  - macos/.zshrc
  - general/.gitignore
  - general/.gitconfig
dotfiles_home: "~"