- hosts: all
  vars:
    zsh_antigen_bundles_extras:
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
  pre_tasks:
    - include_tasks: tasks/zsh.local.yml
  roles:
    - viasite-ansible.zsh
    